{% set name = "honcho" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/honcho-{{ version }}.tar.gz
  sha256: af3815c03c634bf67d50f114253ea9fef72ecff26e4fd06b29234789ac5b8b2e

build:
  noarch: python
  entry_points:
    - honcho=honcho.command:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - colorama

test:
  imports:
    - honcho
  commands:
    - pip check
    - honcho --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nickstenning/honcho
  summary: Python clone of Foreman for managing Procfile-based applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
